### ISSUE TITLE
Code style issue

### ISSUE THREAD

**Issue by Adrijaned** [Sigma-One/sigma-one.github.io#2]
Why are there closing `>`s in `factorio.html` on new lines? They have nothing to do on the next lines. Move to the lines they belong to.

**Comment by Adrijaned** [comment]
In `index.html` too.

**Comment by Sigma-One** [comment]
it is because otherwise the links that have `inline-block` display would have gaps between them. It seems that the weird newline thing is a workaround.

**Comment by Adrijaned** [comment]
WTF HTML???

**Comment by Sigma-One** [comment]
More like WTF CSS?
